version: '3'
services:
  app:
    build: .
    image: reaculator
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development